<?php 
	$code = $block->escapeHtml($block->getMethodCode()); 
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?php echo $code; ?>" style="display:none">
	<iframe style="border:none;"
		id="monetra-payment-iframe"
		data-payment-form-host="<?php echo $block->getMonetraUrl() ?>"
		data-hmac-hmacsha256="<?php echo $block->getMonetraHmac() ?>"
		data-hmac-timestamp="<?php echo $block->getMonetraTimestamp() ?>"
		data-hmac-domain="<?php echo $block->getHostDomain() ?>"
		data-hmac-sequence="<?php echo $block->getMonetraSequence() ?>"
		data-hmac-username="<?php echo $block->getMonetraUsername() ?>"
		data-hmac-css-url=""
		data-hmac-include-cardholdername="no"
		data-hmac-include-street="no"
		data-hmac-include-zip="no"
		data-hmac-expdate-format="single-text"
		data-hmac-auto-reload="no"
		data-hmac-autocomplete="no"
		data-hmac-include-submit-button="no">
	</iframe>
	<div id="monetra_client_ticket_response_fields"></div>
</fieldset>
<script>
	require(["Monetra_Monetra/js/client-ticket"]);
</script>
