<?php 
	$code = $block->escapeHtml($block->getMethodCode()); 
?>
<fieldset data-mage-init='{
		"Monetra_Monetra/js/client-ticket": {}
	}' class="admin__fieldset payment-method" id="payment_form_<?php echo $code; ?>" style="display:none">
	<iframe style="border:none;"
		id="monetra-payment-iframe"
		data-payment-form-host="<?php echo $block->getMonetraUrl() ?>"
		data-hmac-hmacsha256="<?php echo $block->getMonetraHmac() ?>"
		data-hmac-timestamp="<?php echo $block->getMonetraTimestamp() ?>"
		data-hmac-domain="<?php echo $block->getHostDomain() ?>"
		data-hmac-sequence="<?php echo $block->getMonetraSequence() ?>"
		<?php if ($block->usingApiKey()) {
			$auth_field_name = "auth_apikey_id";
			$auth_field_value = $block->getMonetraApiKeyId();
		} else {
			$auth_field_name = "username";
			$auth_field_value = $block->getMonetraUsername();
		} ?>
		data-hmac-<?php echo $auth_field_name ?>="<?php echo $auth_field_value ?>"
		data-hmac-css-url="<?php echo $block->getCssUrl() ?>"
		data-hmac-include-cardholdername="no"
		data-hmac-include-street="no"
		data-hmac-include-zip="no"
		data-hmac-expdate-format="<?php echo $block->getExpdateFormat() ?>"
		data-hmac-auto-reload="<?php echo $block->getAutoReload() ?>"
		data-hmac-autocomplete="<?php echo $block->getAutocomplete() ?>"
		data-hmac-include-submit-button="no">
	</iframe>
	<div id="monetra_client_ticket_response_fields"></div>
	<?php if ($block->isVaultEnabled()) : ?>
		<div class="field-tooltip-content">
			<input type="checkbox"
				id="<?= $block->escapeHtmlAttr($code) ?>_vault"
				name="payment[<?= $block->getVaultIsActiveCode() ?>]"
				class="admin__control-checkbox"
				value="1" />
			<label class="label" for="<?= $block->escapeHtmlAttr($code) ?>_vault">
				<span><?= $block->escapeHtml('Save for later use.') ?></span>
			</label>
		</div>
	<?php endif; ?>
</fieldset>
